# ${project.build.finalName} Config

# Version
version: 1.0

# Settings
settings:

  # The prefix to use for permissions
  permissionPrefix: ${project.permissionprefix}

  # Should extra information be logged? (Only useful for bug testing)
  debug: false

  # What language should be used when sending messages?
  language: en

  # What prefix should be used for the plugin? | {name} is replaced with the plugin name
  prefix: "&f[&r&b{name}&r&f]"

  # Trade Settings
  trade:

    # How many minutes can a trade idle for before being canceled?
    cancelTime: 2

    # How many seconds does a player have to unready before a trade completes?
    tickDownCounter: 7

    # Should players in creative be allowed to trade?
    allowCreativeTrading: false

    # Trade interface Settings
    interface:

      # What name should be used for the trade menu?
      name: "&bTrade Menu"

      # Entry Settings
      entry:

       # Toggle Readiness for trader entry
        toggleReadinessTrader:

          # What named should be used for this entry? | {name} - the name of the player
          name: "&bToggle Readiness ({name})"

          # What lore should be added to this entry?
          lore:
          - "Click to mark yourself as ready for this trade!"

       # Toggle Readiness for tradee entry
        toggleReadinessTradee:

          # What named should be used for this entry?
          name: "&bToggle Readiness ({name})"

          # What lore should be added to this entry?
          lore:
          - "Click to mark yourself as ready for this trade!"

       # Trade Info entry
        tradeInfo:

          # What named should be used for this entry?
          name: "&bTrade Info"

       # Remind Player entry
        remindPlayer:

          # What named should be used for this entry?
          name: "&bRemind Player of Trade"

          # What lore should be added to this entry?
          lore:
          - "Click to remind other player of the trade!"

       # Add one currency entry
        addOneCurrency:

          # What named should be used for this entry? | {currency-#} - the currency formatted for a certain #
          name: "&bAdd {currency-1}"

          # What lore should be added to this entry? | {currency-#} - the currency formatted for a certain #
          lore:
          - "Click to add {currency-1} to the trade."
          - "Shift Click to add {currency-10} to the trade"

       # Remove one currency entry
        removeOneCurrency:

          # What named should be used for this entry? | {currency-#} - the currency formatted for a certain #
          name: "&bRemove {currency-1}"

          # What lore should be added to this entry? | {currency-#} - the currency formatted for a certain #
          lore:
          - "Click to remove {currency-1} from the trade."
          - "Shift Click to remove {currency-10} from the trade"

       # Add Ten currency entry
        addTenCurrency:

          # What named should be used for this entry? | {currency-#} - the currency formatted for a certain #
          name: "&bAdd {currency-10}"

          # What lore should be added to this entry? | {currency-#} - the currency formatted for a certain #
          lore:
          - "Click to add {currency-10} to the trade."
          - "Shift Click to add {currency-100} to the trade"

       # Remove Ten currency entry
        removeTenCurrency:

          # What named should be used for this entry? | {currency-#} - the currency formatted for a certain #
          name: "&bRemove {currency-10}"

          # What lore should be added to this entry? | {currency-#} - the currency formatted for a certain #
          lore:
          - "Click to remove {currency-10} from the trade."
          - "Shift Click to remove {currency-100} from the trade"

       # Cancel Trade entry
        cancelTrade:

          # What named should be used for this entry?
          name: "&bCancel Trade"

          # What lore should be added to this entry?
          lore:
          - "Click to cancel this trade!"