name: ${project.name}
version: ${project.version}
authors: [${project.authors}]
main: ${project.main}
depend: [${project.depends}]
softdepend: [${project.softdepends}]

commands:
  ${project.name.lowercase}:
    description: master command system for the plugin
    usage: "${project.name.short} Usage: /${project.name.short} help"
    aliases: [${project.name.short}]
  trade:
    description: command used for trading
    usage: "/trade Usage: /trade help"
permissions:

  # Parent Nodes
  ${project.permissionprefix}.sysadmin:
    description: "Gives system administrator level permissions, includes all lower levels."
    children:
      ${project.permissionprefix}.admin: true
      ${project.permissionprefix}.commands.reload: true
    default: op
  ${project.permissionprefix}.admin:
    description: "Gives administrator level permissions, includes all lower levels."
    children:
      ${project.permissionprefix}.commands.book: true
    default: op

  # Singular Nodes
  ${project.permissionprefix}.commands.reload:
    description: "Allows use of the reload subcommand"
    default: op